# Site settings
title: Chris Jeakle | Home
email: cjjeakle@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Christopher Jeakle's web site. Check out what I am up to and the things I am working on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chrisjeakle.com" # the base hostname & protocol for your site
github_username:  cjjeakle

# Build settings
markdown: kramdown
